name=input("enter the number of a person: ")
address=int(input("enter the house number: "))
place=input("enter the nearest place: ")
email=input("enter the email: ")
phone_number=int(input("enter the number: "))
print("details of the person: ",name,address,place,email,phone_number)